### PR TITLE
Bug 2073373: Rebase to v1.16.0

### PR DESCRIPTION
**Pull request by jsafrane**
Diff to upstream v1.16.0:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/compare/v1.16.0...jsafrane:rebase-v1.15.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Unit tests use wrong golang image, fix: https://github.com/openshift/release/pull/27691

**Comment by jsafrane** [comment]
Installation of e2e-azure-csi failed because the CSI driver was not able to provision volumes for metrics PVCs:

```
I0408 11:33:19.049347       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateVolume
I0408 11:33:19.049371       1 utils.go:78] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":""}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":""}}]},"capacity_range":{"required_bytes":21474836480},"name":"pvc-b5174048-1905-4516-9ab7-9a191e1172c7","parameters":{"kind":"Managed","storageaccounttype":"Premium_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}}]}
I0408 11:33:19.049530       1 controllerserver.go:170] begin to create azure disk(pvc-b5174048-1905-4516-9ab7-9a191e1172c7) account type(Premium_LRS) rg(ci-op-6t4f49l0-6a9e9-bhzl6-rg) location(westus) size(20) diskZone() maxShares(0)
I0408 11:33:33.991920       1 azure_armclient.go:163] response is empty
E0408 11:33:33.992047       1 utils.go:82] GRPC error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: context canceled
I0408 11:33:34.050115       1 azure_armclient.go:163] response is empty
E0408 11:33:34.050214       1 utils.go:82] GRPC error: Retriable: true, RetryAfter: 0s, HTTPStatusCode: -1, RawError: context deadline exceeded
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_azure-disk-csi-driver/24/pull-ci-openshift-azure-disk-csi-driver-master-e2e-azure/1512381610035515392/artifacts/e2e-azure/gather-extra/artifacts/pods/openshift-cluster-csi-drivers_azure-disk-csi-driver-controller-bdcb766cd-h4qmj_csi-driver.log

Investigating...

**Comment by jsafrane** [comment]
/test all
With new golang from https://github.com/openshift/release/pull/27691

**Comment by jsafrane** [comment]
/hold
for QE testing

**Review by bertinatto — COMMENTED** [review]
In upstream they install btrfs-progs. Do we want to support btrfs as well?

In any case, changes LGTM:

/lgtm

**Comment by jsafrane** [comment]
Updated to upstream's v1.16.0 release.

**Comment by jsafrane** [comment]
This should fix also [Bug 2074281](https://bugzilla.redhat.com/show_bug.cgi?id=2074281)

**Comment by bertinatto** [comment]
Did another check after for v1.16.0 update.
/lgtm

**Comment by jsafrane** [comment]
/retest
One prometheus test failed, but it does not look related to CSI migration

**Pull request merged**
