### PR TITLE
STOR-1016: Rebase to v1.26.1 for OCP 4.13

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v1.26.1:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/compare/v1.26.1...mpatlasov:rebase-1.26.1-again

Major changes between 1.22 (OCP 4.12) and 1.26.1:

support perf profile device setting on Linux node (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1596)
vmss flex mode support (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1587, https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1563)
support PremiumV2_LRS disk type (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1477)
support location in storage class (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1497)

Full changelogs:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.26.1
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.26.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.25.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.24.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.23.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Loki pods did not start. It's odd that it happened in both e2e jobs...

> alert/KubePodNotReady ns/openshift-e2e-loki pod/loki-promtail-5msmr ALERTS{alertname="KubePodNotReady", alertstate="firing", namespace="openshift-e2e-loki", pod="loki-promtail-5msmr", prometheus="openshift-monitoring/k8s", severity="warning"}

**Comment by jsafrane** [comment]
I checked [loki pod `loki-promtail-2lg68`](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_azure-disk-csi-driver/37/pull-ci-openshift-azure-disk-csi-driver-master-e2e-azure-csi/1618099599954677760/artifacts/e2e-azure-csi/gather-extra/artifacts/pods.json), it did not start because of:

```json
"state": {
    "waiting": {
          "message": "Back-off pulling image \"registry.redhat.io/openshift4/ose-oauth-proxy:latest\"",
          "reason": "ImagePullBackOff"
     }
```

**Comment by dobsonj** [comment]
Same error again, failing to pull `ose-oauth-proxy:latest`
/retest

**Comment by jsafrane** [comment]
Major changes between 1.22 (OCP 4.12) and 1.26.1 that caught my eye:

* support perf profile device setting on Linux node (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1596)
* vmss flex mode support (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1587, https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1563)
* support PremiumV2_LRS disk type (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1477)
* support location in storage class (https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1497)

(I am not sure what most of the features actually mean)

Full changelogs:
* https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.26.1
* https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.26.0
* https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.25.0
* https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.24.0
* https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.23.0

(@mpatlasov, this should be in the first message to tell QE what to expect from the rebase. I updated our rebase docs accordingly)

/lgtm

**Comment by duanwei33** [comment]
The  basic test for the following features:
support perf profile device setting on Linux node
support PremiumV2_LRS disk type
support location in storage class

Also did not see regression issue.

**Pull request merged**
