### PR TITLE
OCPBUGS-22941: UPSTREAM: 1755: fix: detach disk failure when there is throttling

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

Please review carefully because this wasn't a clean pick. https://github.com/kubernetes-sigs/cloud-provider-azure/pull/3482 is the original patch.

### CODE REVIEW

**Comment by sdodson** [comment]
Looks like a legitimate test failure.

**Comment by gnufied** [comment]
So this PR modifies vendor directly and hence it is indeed a legitimate failure, but we were kinda options here, so we are sort of doing this as last resort. Any direct modification to vendor has danger of getting wiped away if someone does `go mod download && go mod vendor`, but hopefully we won't be doing this in 4.12..

**Pull request merged**
