### PR TITLE
STOR-864: Rebase to v1.22.0 for OCP 4.12

### PR DESCRIPTION
**Pull request by RomanBednar**
Diff to upstream v1.22.0:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/compare/v1.22.0...RomanBednar:rebase-v1.22.0

Notable changes since v1.16.0

Features:
- Add DiskEncryptionType in storage class #1315

Helm chart upgrades:
- Add controller.vmssCacheTTLInSeconds in helm chart config #1287
- Add controller.runOnControlPlane in chart config #1366
- Add affinity, nodeSelector in chart config #1377

Others:
- sidecar version bumps
- bug fixes
- new tests

Changelogs:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.17.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.18.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.19.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.20.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.21.0
https://github.com/kubernetes-sigs/azuredisk-csi-driver/releases/tag/v1.22.0

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
`Code="OSProvisioningTimedOut" Message="OS Provisioning for VM 'ci-op-pwwqipbm-36867-v8dlq-master-0' did not finish in the allotted time.`

/retest

**Comment by jsafrane** [comment]
@RomanBednar Please go through changelog(s) and list important features in the PR description. Also, please link the changelogs, so QA knows what to test / where a regression could be. See https://github.com/openshift/azure-file-csi-driver/pull/17 as an example

**Comment by RomanBednar** [comment]
> @RomanBednar Please go through changelog(s) and list important features in the PR description. Also, please link the changelogs, so QA knows what to test / where a regression could be. See [openshift/azure-file-csi-driver#17](https://github.com/openshift/azure-file-csi-driver/pull/17) as an example

Added.

**Comment by RomanBednar** [comment]
`failed to create RBAC objects: timeout while waiting for dockercfg secret creation for service account "e2e-azure-csi": timed out waiting for the condition`

/retest

**Comment by jsafrane** [comment]
CI failures look unrelated:
>: [bz-Networking][invariant] alert/KubePodNotReady should not be at or above info in ns/openshift-multus

**Comment by duanwei33** [comment]
Pre-merge verified passed with regression test, no issue found.
For the new feature, created new storageclass with  "diskEncryptionType": "EncryptionAtRestWithPlatformAndCustomerKeys", and create pvc/pod works. 

```
$ oc get sc managed-csi-test-24 -ojson | jq .parameters
{
  "diskEncryptionType": "EncryptionAtRestWithPlatformAndCustomerKeys",
  "diskencryptionsetid": "/subscriptions/53b8f551-f0fc-4bea-8cba-6d1fefd54c8a/resourceGroups/wduan-0917b-az-r264r-rg/providers/Microsoft.Compute/diskEncryptionSets/wduan-1",
  "kind": "Managed",
  "skuname": "Premium_LRS"
}
```

Check in the backend:
`Encryption type: Double encryption with platform-managed and customer-managed keys.
`

/label qe-approved

**Comment by jsafrane** [comment]
/label docs-approved
/label px-approved

We don't document / announce CSI driver version bumps to customers.

**Pull request merged**
