### PR TITLE
Bug 2111811: UPSTREAM 1367, 1409: Update max data disk count table

### PR DESCRIPTION
**Pull request by tsmetana**
/kind bug

This is a backport of upstream changes that add new node types to the max disc count tables. It should fix the problem with users using older releases of OCP with new Azure node types.

### CODE REVIEW

**Comment by jsafrane** [comment]
/test all
???

**Comment by jsafrane** [comment]
/lgtm
I checked that `azure_dd_max_disk_count.go` is the same as in upstream/master.

**Comment by tsmetana** [comment]
/retest

The failure is not related to the patch. Looks like Azure is just slow in deleting the disks.

**Pull request merged**
