### PR TITLE
Rebase v1.5.0

### PR DESCRIPTION
**Pull request by tjungblu**
several fixes and releases, including fixes for AzureStack Hub:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/compare/v1.5.0...tjungblu:master

CC @openshift/storage

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
Thanks, @tjungblu! 

This looks really good, it seems like you merged the tag `v1.5.0` into `openshift/master` and provided a link in the description that shows the diff between your branch and the upstream `v1.5.0` tag.

I just have a small nit that would be interesting if you could fix, but it's not a big deal: we typically don't use our `master` branches to submit PRs, we usually create a custom branch for that, like `release-v1.5.0`.

A good side effect of that is that the link you provided in the description will not stop working once you overwrite your master branch. :)

**Comment by bertinatto** [comment]
BTW, the test failure seems unrelated to this PR.

**Comment by tjungblu** [comment]
> A good side effect of that is that the link you provided in the description will not stop working once you overwrite your master branch. :)

is there a more sustainable solution for this? I intend to completely remove my forked repo after my time on the storage team.

As for the test failure, I already reached out to Mustafa to have a look (I believe he was working on that).

**Comment by Elbehery** [comment]
> As for the test failure, I already reached out to Mustafa to have a look (I believe he was working on that).

@tjungblu these failing tests are not related to your changes as @bertinatto said. Once we rebase upstream v1.21, all of prometheus WAL problems will be resolved, I hope :)

**Comment by bertinatto** [comment]
> > A good side effect of that is that the link you provided in the description will not stop working once you overwrite your master branch. :)
> 
> is there a more sustainable solution for this? I intend to completely remove my forked repo after my time on the storage team.
> 
> As for the test failure, I already reached out to Mustafa to have a look (I believe he was working on that).

I'm not sure if there's a better solution for this, but since you intend to remove your fork, I believe we can merge the PR as is. Thanks for working on this.

/lgtm
/approve

**Pull request merged**
