### PR TITLE
OCPBUGS-17542: allow resizing to min required size for performance plus disks

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a cherry-pick of: https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1950

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/hold
for https://github.com/openshift/azure-disk-csi-driver/pull/51 to be merged first (so this does not get lost)

**Comment by duanwei33** [comment]
Performing pre-merge test with this open PR:
```
$ oc get clusterversion
NAME      VERSION                                                AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.15.0-0.test-2023-11-14-060559-ci-ln-bzmt5fb-latest   True        False         110m    Cluster version is 4.15.0-0.test-2023-11-14-060559-ci-ln-bzmt5fb-latest
```

Create sc with enablePerformancePlus: "true" and pvc-1 with size: 512Gi, volume provisioned with 513Gi:
```
$ oc get pvc mypvc-28-sssdlrs-enableperformanceplus-1
NAME                                       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                                        AGE
mypvc-28-sssdlrs-enableperformanceplus-1   Bound    pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0   513Gi      RWO            managed-csi-test-28-sssdlrs-enableperformanceplus   30m


$ oc get pvc mypvc-28-sssdlrs-enableperformanceplus-1 -o json | jq "{"requests": .spec.resources.requests.storage, "capacity": .status.capacity.storage}"
{
  "requests": "512Gi",
  "capacity": "513Gi"
}
```


See log:  "using PerformancePlus, increasing requested disk size from 512GiB to 513GiB (minimal size for PerformancePlus feature)":
```
I1114 09:19:56.799081       1 utils.go:78] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus-2","topology.kubernetes.io/zone":"eastus-2"}},{"segments":{"topology.disk.csi.azure.com/zone":"eastus-3","topology.kubernetes.io/zone":"eastus-3"}},{"segments":{"topology.disk.csi.azure.com/zone":"eastus-1","topology.kubernetes.io/zone":"eastus-1"}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus-1","topology.kubernetes.io/zone":"eastus-1"}},{"segments":{"topology.disk.csi.azure.com/zone":"eastus-2","topology.kubernetes.io/zone":"eastus-2"}},{"segments":{"topology.disk.csi.azure.com/zone":"eastus-3","topology.kubernetes.io/zone":"eastus-3"}}]},"capacity_range":{"required_bytes":549755813888},"name":"pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0","parameters":{"csi.storage.k8s.io/pv/name":"pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0","csi.storage.k8s.io/pvc/name":"mypvc-28-sssdlrs-enableperformanceplus-1","csi.storage.k8s.io/pvc/namespace":"wduan","enablePerformancePlus":"true","skuname":"StandardSSD_LRS"},"volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}}]}
W1114 09:19:56.799304       1 controllerserver.go:103] using PerformancePlus, increasing requested disk size from 512GiB to 513GiB (minimal size for PerformancePlus feature)
I1114 09:19:56.799342       1 controllerserver.go:204] begin to create azure disk(pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0) account type(StandardSSD_LRS) rg(wduan-1114a-az-xc8nl-rg) location(eastus) size(513) diskZone(eastus-2) maxShares(0)
I1114 09:19:59.162153       1 azure_managedDiskController.go:288] azureDisk - created new MD Name:pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0 StorageAccountType:StandardSSD_LRS Size:513
I1114 09:19:59.162189       1 controllerserver.go:300] create azure disk(pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0) account type(StandardSSD_LRS) rg(wduan-1114a-az-xc8nl-rg) location(eastus) size(513) tags(map[kubernetes.io-created-for-pv-name:pvc-0d4db402-e048-4fcf-a152-ec7118cfbad0 kubernetes.io-created-for-pvc-name:mypvc-28-sssdlrs-enableperformanceplus-1 kubernetes.io-created-for-pvc-namespace:wduan]) successfully
```

Also tried pvc-2 with size: 1Gi, volume provisioned with 513Gi:
```
$ oc get pvc mypvc-28-sssdlrs-enableperformanceplus-2 -o json | jq "{"requests": .spec.resources.requests.storage, "capacity": .status.capacity.storage}"
{
  "requests": "1Gi",
  "capacity": "513Gi"
}
```

The behaviour changes a bit compared the previous version, volume size will autoresize to 513G while the pvc request <= 512G when enable the PerformancePlus feature,  I think it is reasonable. And we can note the behaviour somewhere later. 
Thanks for the update!

**Comment by duanwei33** [comment]
@RomanBednar @jsafrane I think we can remove the "hold" if CI looks good :)

**Comment by RomanBednar** [comment]
/unhold

@duanwei33 Indeed, removing hold.

**Pull request merged**
