### PR TITLE
OCPBUGS-18701: UPSTREAM: 1904, UPSTREAM: 1917, UPSTREAM: 1955: Update disk number table

### PR DESCRIPTION
**Pull request by tsmetana**
Cumulative backport of the updated max data disk count table from the latest upstream.

### CODE REVIEW

**Comment by Phaow** [comment]
Use the pre merged build `4.14.0-0.ci.test-2023-09-15-012215-ci-ln-kfslvtk-latest` check the csinode object allocatable volumes count for `Standard_B4as_v2` passed
```console
$ oc get no/pewang-0915s-qhk52-worker-southcentralus1-tqp64 -oyaml| grep 'instance-type'
    beta.kubernetes.io/instance-type: Standard_B4as_v2
    node.kubernetes.io/instance-type: Standard_B4as_v2
$ oc get csinode pewang-0915s-qhk52-worker-southcentralus1-tqp64 -ojsonpath='{.spec.drivers[?(@.name=="disk.csi.azure.com")].allocatable.count}'
8
```

**Comment by RomanBednar** [comment]
@tsmetana Upstream PR #1917 refers to a cherry-pick PR, shouldn't we rather reference #1916 instead which is the origin (in master)? The other two (1904 and 1955) seem ok.

**Pull request merged**
